/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packageimg;

/**
 *
 *
 * @author cruze
 */
public class atualizarCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastro
     */
    public atualizarCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alteraNome = new javax.swing.JTextField();
        alteraCpf = new javax.swing.JTextField();
        alteraData = new javax.swing.JTextField();
        alteraTelefone = new javax.swing.JTextField();
        alteraEmail = new javax.swing.JTextField();
        alteraEndereço = new javax.swing.JTextField();
        alteraCidade = new javax.swing.JTextField();
        alteraCep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alteraNome.setText("Nome completo");
        jPanel1.add(alteraNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 290, -1));

        alteraCpf.setText("CPF");
        jPanel1.add(alteraCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 290, -1));

        alteraData.setText("Data de nascimento");
        jPanel1.add(alteraData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 290, -1));

        alteraTelefone.setText("Telefone");
        jPanel1.add(alteraTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 290, -1));

        alteraEmail.setText("E-mail");
        jPanel1.add(alteraEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 290, -1));

        alteraEndereço.setText("Endereço");
        jPanel1.add(alteraEndereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 250, -1));

        alteraCidade.setText("Cidade");
        jPanel1.add(alteraCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 290, 100, -1));

        alteraCep.setText("CEP");
        jPanel1.add(alteraCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EditarCadastro.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 830, 400));

        btAtualizar.setBackground(new java.awt.Color(51, 255, 153));
        btAtualizar.setText("ATUALIZAR");
        btAtualizar.setContentAreaFilled(false);
        jPanel1.add(btAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atualizarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atualizarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atualizarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atualizarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atualizarCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alteraCep;
    private javax.swing.JTextField alteraCidade;
    private javax.swing.JTextField alteraCpf;
    private javax.swing.JTextField alteraData;
    private javax.swing.JTextField alteraEmail;
    private javax.swing.JTextField alteraEndereço;
    private javax.swing.JTextField alteraNome;
    private javax.swing.JTextField alteraTelefone;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
