/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package packageimg;

/**
 *
 * @author cruze
 */
public class telaMenu extends javax.swing.JPanel {

    /**
     * Creates new form telaMenu
     */
    public telaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloMenu = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tituloMenu.setText("ESCOLHA UMA DAS OPÇÕES ABAIXO:");
        jPanel1.add(tituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 330, 40));

        btConsultar.setBackground(new java.awt.Color(0, 153, 153));
        btConsultar.setText("CONSULTAR");
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 127, 30));

        btEditar.setBackground(new java.awt.Color(0, 153, 153));
        btEditar.setText("EDITAR CADASTROS");
        jPanel1.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 30));

        btCadastrar.setBackground(new java.awt.Color(0, 153, 153));
        btCadastrar.setText("NOVO CADASTRO");
        jPanel1.add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 30));

        btExcluir.setBackground(new java.awt.Color(0, 153, 153));
        btExcluir.setText("EXCLUIR REGISTROS");
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloMenu;
    // End of variables declaration//GEN-END:variables
}
